### ISSUE TITLE
V-model 2 way sync and placeholder

### ISSUE THREAD

**Issue by ashwinkshenoy** [sureshUngarala/vue-components#3]
`v-model` is currently having only 1 way sync. 
Can we get an option for 2 way sync so that on update the v-model also gets updated.

If possible an option for placeholder prop so that we can add custom placeholder.

Thanks

**Comment by sureshungarala** [comment]
Sure. That feels right. Will do. Thanks for using and creating this issue.

**Comment by sureshungarala** [comment]
I released a version([v1.6.23](https://github.com/sureshungarala/vue-components/releases/tag/v1.6.23)) for this. 
Please review and let me know.

**Comment by sureshungarala** [comment]
Released a new version to fix placeholder placement([v1.7.1](https://github.com/sureshungarala/vue-components/releases/tag/v1.7.1)).

**Comment by sureshungarala** [comment]
Closing this as Done.
